### ISSUE TITLE
 PVA backend does not correctly handle long-string waveforms.

### ISSUE THREAD

**Issue by jwlodek** [bluesky/ophyd-async#678]
When attempting to connect to waveform records with the PVA backend, we get a type error:

```
NotConnected: 
manta_async: NotConnected:
    drv: NotConnected:
        nd_attributes_file: TypeError: XF:31ID1-ES{GigE-Cam:1}cam1:NDAttributesFile with inferred datatype Array1D[np.int8] from typeid='epics:nt/NTScalarArray:1.0' specifier='ab' cannot be coerced to str
    fileio: NotConnected:
        xml_file_name: TypeError: XF:31ID1-ES{GigE-Cam:1}HDF1:XMLFileName_RBV with inferred datatype Array1D[np.int8] from typeid='epics:nt/NTScalarArray:1.0' specifier='ab' cannot be coerced to str
        file_path: TypeError: XF:31ID1-ES{GigE-Cam:1}HDF1:FilePath_RBV with inferred datatype Array1D[np.int8] from typeid='epics:nt/NTScalarArray:1.0' specifier='ab' cannot be coerced to str
        file_name: TypeError: XF:31ID1-ES{GigE-Cam:1}HDF1:FileName_RBV with inferred datatype Array1D[np.int8] from typeid='epics:nt/NTScalarArray:1.0' specifier='ab' cannot be coerced to str
        file_template: TypeError: XF:31ID1-ES{GigE-Cam:1}HDF1:FileTemplate_RBV with inferred datatype Array1D[np.int8] from typeid='epics:nt/NTScalarArray:1.0' specifier='ab' cannot be coerced to str
        full_file_name: TypeError: XF:31ID1-ES{GigE-Cam:1}HDF1:FullFileName_RBV with inferred datatype Array1D[np.int8] from typeid='epics:nt/NTScalarArray:1.0' specifier='ab' cannot be coerced to str
        nd_attributes_file: TypeError: XF:31ID1-ES{GigE-Cam:1}HDF1:NDAttributesFile with inferred datatype Array1D[np.int8] from typeid='epics:nt/NTScalarArray:1.0' specifier='ab' cannot be coerced to str
```

This is because the type provided by PVA is an array of ints, rather than a string.

## Steps To Reproduce
1. Install ophyd async with p4p only.
2. Attempt to connect to a waveform signal with FTVL= CHAR.

## Acceptance Criteria
- Can connect to waveform records as strings if FTVL=CHAR when using the PVA backend
