### ISSUE TITLE
Support new pvi structure

### ISSUE THREAD

**Issue by evalott100** [bluesky/ophyd-async#761]
FastCS will use a different pvi structure for its p4p backend:

https://github.com/DiamondLightSource/FastCS/pull/119#issuecomment-2651282099

Swapping from:

``` yaml
value:
  pulse:
    - null
    - d: PANDA:PULSE1:PVI
    - d: PANDA:PULSE2:PVI
```

with null for missing indices, e.g 0 in the above, to

```
value:
  pulse:
    d:
      v1: PANDA:PULSE1:PVI
      v2: PANDA:PULSE2:PVI
```

Both the new and old layout should be supported.
